id: A9D9D0099
title: Toh_103-The_Teaching_by_the_Child_Inconceivable_Radiance-v2
type: translation
pechas:
- I6FB3A337
- I74547072
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-048-003
  eft-text-version: 1.0.10 2021
  title: Toh_103-The_Teaching_by_the_Child_Inconceivable_Radiance-v2
alignment_to_base:
  I6FB3A337/A490: 49D1
  I74547072/8ADA: 49D1
